Data_Preparation:
  test_size: 0.25
  random_state: 42

Train:
  Random_Forest:
    n_estimators:  350
    criterion: 'squared_error'
    max_depth: 22
    min_samples_split: 10
    min_samples_leaf: 2
    max_samples: 0.6929749774146244
    verbose: 1
    n_jobs: -1
  